temp/objects/Airport__c.object
<CustomObject>
    <description>A place for airplanes to arrive to and depart from</description>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Total_Flied_Hours__c</fullName>
        <label>Total Flied Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Jet__c.object
<CustomObject>
    <description>A private airplane</description>
    <fields>
        <fullName>Airport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Airport where the Jet is currently located</description>
        <label>Current Airport Location</label>
        <referenceTo>Airport__c</referenceTo>
        <relationshipLabel>Jets</relationshipLabel>
        <relationshipName>Jets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Min_Required_Pilot_Hours__c</fullName>
        <description>Minimum amount flied hors needed for pilot to fly on this jet</description>
        <label>Min Required Pilot Hours</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Flied_Hours__c</fullName>
        <label>Total Flied Hours</label>
        <summarizedField>Jet_Booking__c.Hours_spent__c</summarizedField>
        <summaryFilterItems>
            <field>Jet_Booking__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Jet_Booking__c.Jet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Jet</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Jet_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Arival_Airport__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The airport to which the jet will arrive</description>
        <label>Arival Airport</label>
        <referenceTo>Airport__c</referenceTo>
        <relationshipLabel>Jet Bookings (Arival Airport)</relationshipLabel>
        <relationshipName>Jet_Bookings1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <description>A person who booked the plane</description>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Jet Bookings</relationshipLabel>
        <relationshipName>Jet_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Departure_Airport__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The airport from which the jet will depart</description>
        <label>Departure Airport</label>
        <referenceTo>Airport__c</referenceTo>
        <relationshipLabel>Jet Bookings</relationshipLabel>
        <relationshipName>Jet_Bookings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Jet__c</fullName>
        <description>Booked Jet</description>
        <label>Target Jet Model</label>
        <referenceTo>Jet__c</referenceTo>
        <relationshipLabel>Jet Bookings</relationshipLabel>
        <relationshipName>Jet_Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Automatically Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Jet Booking</label>
    <nameField>
        <displayFormat>BK{0000}</displayFormat>
        <label>Jet Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jet Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Jet__c> createJets(Integer numJets) {
        List<Jet__c> jets = new List<Jet__c>();
        
        for(Integer i=0;i<numJets;i++) {
            Jet__c a = new Jet__c(Name='TestJet' + i, Min_Required_Pilot_Hours__c=100);
            jets.add(a);
        }
        insert jets;
        
        return jets;
    }

    public static Jet_Booking__c createJetBooking() {
        Set<sObject> objectsToInsert = new Set<sObject>();
        Customer__c customer = new Customer__c(Name='TestCustomer',Total_Flied_Hours__c=200);
        insert customer;
        // objectsToInsert.add(customer);
        Airport__c departureAirport = new Airport__c(Name='TestDepartureAirport');
        insert departureAirport;
        // objectsToInsert.add(departureAirport);
        Airport__c arivalAirport = new Airport__c(Name='TestArivalAirport');
        insert arivalAirport;
        // objectsToInsert.add(arivalAirport);
        Jet__c jet = new Jet__c(Name='TestJet', Min_Required_Pilot_Hours__c=100);
        insert jet;
        // objectsToInsert.add(jet);
        Jet_Booking__c jetBooking = new Jet_Booking__c(Customer__c=customer.id, Jet__c=jet.id, Departure_Airport__c=departureAirport.id,
        Arival_Airport__c=arivalAirport.id, Status__c='Created');
        insert jetBooking;
        // objectsToInsert.add(jetBooking);
        return jetBooking;
    }
}