temp/objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Total_Flied_Hours__c</fullName>
        <label>Total Flied Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Jet__c.object
<CustomObject>
    <description>A private airplane</description>
    <fields>
        <fullName>Min_Required_Pilot_Hours__c</fullName>
        <description>Minimum amount flied hors needed for pilot to fly on this jet</description>
        <label>Min Required Pilot Hours</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Flied_Hours__c</fullName>
        <label>Total Flied Hours</label>
        <summarizedField>Jet_Booking__c.Hours_spent__c</summarizedField>
        <summaryFilterItems>
            <field>Jet_Booking__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Jet_Booking__c.Jet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Jet</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Jet_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <description>A person who booked the plane</description>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Jet Bookings</relationshipLabel>
        <relationshipName>Jet_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Jet__c</fullName>
        <description>Booked Jet</description>
        <label>Target Jet Model</label>
        <referenceTo>Jet__c</referenceTo>
        <relationshipLabel>Jet Bookings</relationshipLabel>
        <relationshipName>Jet_Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Automatically Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Jet Booking</label>
    <nameField>
        <displayFormat>BK{0000}</displayFormat>
        <label>Jet Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jet Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/triggers/JetBookingTriggerHandler.cls
public with sharing class JetBookingTriggerHandler {
    public JetBookingTriggerHandler() {

    }
    
    public static void onBeforeInsert(List<Jet_Booking__c> insertdList) {
        for (Jet_Booking__c booking : insertdList) {
            System.debug('Pilot flied hours: ' + booking.Customer__r.Total_Flied_Hours__c);
            System.debug('Jet required flied hours: ' + booking.Jet__r.Min_Required_Pilot_Hours__c);
            if (booking.Customer__r.Total_Flied_Hours__c >= booking.Jet__r.Min_Required_Pilot_Hours__c) {
                System.debug('Pilot is good. Approve automatically');
                booking.Status__c = 'Automatically Approved';
            }
            
            else if (booking.Customer__r.Total_Flied_Hours__c < booking.Jet__r.Min_Required_Pilot_Hours__c) {
                ApprovalProcessHelper.submitAndProcessApprovalRequest(booking);
                System.debug('Pilot is not good. Submit aprooval request');
                booking.Status__c = 'Approved';
            }
        }
    }

    public static void onBeforeUpdate(Map<id, Jet_Booking__c> insertdNewMap, Map<id, Jet_Booking__c> insertdOldMap) {
        List<Jet_Booking__c> bookingsToUpdate = new List<Jet_Booking__c>();

        for (Jet_Booking__c booking : insertdNewMap.values()) {
            System.debug('Pilot flied hours: ' + booking.Customer__r.Total_Flied_Hours__c);
            System.debug('Jet required flied hours: ' + booking.Jet__r.Min_Required_Pilot_Hours__c);
            if (booking.Customer__r.Total_Flied_Hours__c >= booking.Jet__r.Min_Required_Pilot_Hours__c) {
                booking.Status__c = 'Automatically Approved';
                bookingsToUpdate.add(booking);
            }
            
            else if (booking.Customer__r.Total_Flied_Hours__c < booking.Jet__r.Min_Required_Pilot_Hours__c) {
                ApprovalProcessHelper.submitAndProcessApprovalRequest(booking);
                booking.Status__c = 'Approved';
                bookingsToUpdate.add(booking);
            }
        }
        
        update bookingsToUpdate;
    }
}