temp/objects/Jet__c.object
<CustomObject>
    <description>A private airplane</description>
    <fields>
        <fullName>Next_Inspection__c</fullName>
        <description>The date of next ispection</description>
        <label>Next Inspection</label>
        <type>Date</type>
    </fields>
    <label>Jet</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Jet_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Hours_spent__c</fullName>
        <description>Hour spent on this booking</description>
        <label>Hours spent</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jet__c</fullName>
        <description>Booked Jet</description>
        <label>Target Jet Model</label>
        <referenceTo>Jet__c</referenceTo>
        <relationshipLabel>Jet Bookings</relationshipLabel>
        <relationshipName>Jet_Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Jet Booking</label>
    <nameField>
        <displayFormat>BK{0000}</displayFormat>
        <label>Jet Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jet Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/JetTriggerTest.cls
@isTest
public with sharing class JetTriggerTest {

    @IsTest public static void testJetFliedHours(){
        // List<Jet__c> createdJets = TestDataFactory.createJets(3);
        User u = [select name, Id  FROM user WHERE Alias = 'UUser'];
        Jet_Booking__c jetBooking = TestDataFactory.createJetBooking();
    
        Test.startTest();
        System.runAs(u){
            jetBooking.Hours_spent__c=1005;
            update jetBooking;
        }
        Test.stopTest();

        Jet__c jet = Database.query('SELECT Id FROM Jet__c WHERE Id=' + jetBooking.Jet__c);
        Date d = Date.today().addDays(14);
        Datetime dt = (DateTime)d;
        String dayOfWeek = dt.format('EEEE');
        if (dayOfWeek.equals('Saturday')) {
            d.addDays(2);
        } else if (dayOfWeek.equals('Sunday')) {
            d.addDays(1);
        }
        System.assertEquals(jet.Next_Inspection__c, d);
    }
}