temp/objects/Jet__c.object
<CustomObject>
    <description>A private airplane</description>
    <fields>
        <fullName>Current_Milage__c</fullName>
        <label>Current Milage</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Jet</label>
    <nameField>
        <label>Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Jet_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Jet__c</fullName>
        <description>Booked Jet</description>
        <label>Target Jet Model</label>
        <referenceTo>Jet__c</referenceTo>
        <relationshipLabel>Jet Bookings</relationshipLabel>
        <relationshipName>Jet_Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Automatically Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Jet Booking</label>
    <nameField>
        <displayFormat>BK{0000}</displayFormat>
        <label>Jet Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jet Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/JetExp.cls
public with sharing class JetExp {
    @AuraEnabled(cacheable=true)
    public static List<Jet__c> getJetList() {
       List<Jet__c> jetList= [SELECT Name, Status__c, Current_Milage__c, Details__c FROM Jet__c];
        return jetList;
    }

    @AuraEnabled(cacheable=true)
    public static List<Jet_Booking__c> getJetBookingList(Id jetId) {
        List<Jet_Booking__c> jetBookingList;
        try {
            jetBookingList = [SELECT Name, Status__c FROM Jet_Booking__c WHERE Id = :jetId WITH SECURITY_ENFORCED];
        } catch(System.QueryException qe) {
            System.debug(qe.getMessage());
        }
        return jetBookingList;
    }
}