temp/objects/Jet_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Automatically Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Jet Booking</label>
    <nameField>
        <displayFormat>BK{0000}</displayFormat>
        <label>Jet Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jet Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/JetBookingTriggerTest.cls
@isTest
public with sharing class JetBookingTriggerTest {


    @IsTest public static void testSufficientPilotHours(){
        User u = [select name, Id  FROM user WHERE Alias = 'UUser'];
        Jet_Booking__c jetBooking = TestDataFactory.createJetBooking();
        Test.startTest();
        System.runAs(u){

        }
        Test.stopTest();

        System.assert(jetBooking.Status__c=='Automatically Approved');
    }
}